### ISSUE TITLE
[Feature Request] Default-View per Screen Resolution / Orientation einstellbar

### ISSUE THREAD

**Issue by Giermann** [hobbyquaker/DashUI#105]
Ich hoffe, ich bin hier richtig, wenn es um Feature Requests geht :)

Ich fange gerade erst mit DashUI an, stelle aber schon fest: hier ist noch Platz zum Austoben!
Ich möchte das gern mit dem Smartphone und dem PC nutzen. Der erste Ansatz wäre: am PC einfach einen anderen View wählen, gern auch im Link, den Defaultview fürs Smartphone optimieren, dann passt das schon.
Tja - leider nicht: denn ein Smartphone gibt es Portrait oder Landscape.
Nun habe ich mal ein wenig gegoogelt und stelle fest, dass man mit HTML5 eigentlich die Screen Orientation auslesen kann - sofern der Browser das unterstützt.
http://www.sitepoint.com/using-device-orientation-html5/
Könnte man sowas direkt in DashUI einbauen und sogar auf dynamische Änderung reagieren?
Also man könnte doch immer korrespondierende Views anlegen "#MeinView-portrait" und "#MeinView-landscape" und dann immer wechseln?! Besser natürlich auch noch für die unterschiedlichsten Auflösungen, aber da wird's sicher problematisch, das allgemeingültig umzusetzen, wenn man niemanden zwingen will, für ALLE Auflösungen einen eigenen View zu basteln.

**Comment by GermanBluefox** [comment]
Interessanter Vorschlag. DashUI ist aber gestoppt. Kannst du so was gegen ioBroker.vis schreiben. Das ist neuer Name für Dashui
